import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import { mkdir, writeFile, copyFile } from 'node:fs/promises';
import path from 'node:path';

const baseURL = process.env.DEMO_BASE_URL || 'http://127.0.0.1:3000';
if (!/^http:\/\/(127\.0\.0\.1|localhost)(:\d+)?$/.test(baseURL)) throw new Error('Recording is restricted to a fresh local fixture server.');
const out = path.resolve('artifacts/demo');
await mkdir(out, { recursive: true });
const reset = await fetch(`${baseURL}/api/reset`, { method:'POST',headers:{'content-type':'application/json'},body:'{}' });
assert.equal(reset.status, 200);
const browser = await chromium.launch({ headless:true });
const context = await browser.newContext({ viewport:{width:1440,height:1000}, deviceScaleFactor:1, recordVideo:{dir:out,size:{width:1440,height:1000}}, reducedMotion:'reduce' });
const page = await context.newPage();
const errors = [];
page.on('pageerror', error => errors.push(error.message));
const subtitle = [];
const started = Date.now();
let frame = 0;
let success = false;
const clock = () => (Date.now()-started)/1000;
const apiState = async () => (await fetch(`${baseURL}/api/state`)).json();
async function scene(text, seconds=8, name='scene') {
  const begin=clock();
  await page.screenshot({path:path.join(out,`${String(++frame).padStart(2,'0')}-${name}.png`),fullPage:false});
  await page.waitForTimeout(seconds*1000);
  subtitle.push({begin,end:clock(),text});
}
async function click(action) { await page.locator(`[data-action="${action}"]`).click(); }
function srtTime(s) { const ms=Math.round(s*1000); return `${String(Math.floor(ms/3600000)).padStart(2,'0')}:${String(Math.floor(ms/60000)%60).padStart(2,'0')}:${String(Math.floor(ms/1000)%60).padStart(2,'0')},${String(ms%1000).padStart(3,'0')}`; }
try {
  await page.goto(baseURL,{waitUntil:'networkidle'});
  await page.getByRole('heading',{name:'Teach your cameras what matters.'}).waitFor();
  assert.match(await page.locator('.fixture-tag').textContent(),/SYNTHETIC/);
  await scene('ShowOnce: teach an observable event, test its boundary, and publish evidence.\nSYNTHETIC QA ONLY. No live provider execution or model accuracy is claimed.',10,'opening');
  await click('play');
  await page.waitForFunction(() => document.querySelector('#evidence-video')?.currentTime > 0.5);
  await scene('The positive example: a vehicle remains stopped in a travel lane.\nWatch the source clip, then define what should count.',11,'positive-video');
  await click('generate');
  await page.locator('[data-action="evaluate"]:enabled').waitFor();
  let state=await apiState();
  assert.equal(state.versions.length,1);
  await scene('The first explicit rule is a starting hypothesis.\nIts definition, examples, and provenance are visible.',8,'first-rule');
  await click('evaluate');
  await page.locator('.scoreboard').waitFor();
  state=await apiState();
  assert.equal(state.evaluations.at(-1).metrics.correct,4);
  assert.equal(state.evaluations.at(-1).metrics.falsePositives,2);
  assert.equal(await page.locator('[data-action="publish"]').isEnabled(),false,'Failed validation must block publication');
  await scene('The first fixture check finds two false alerts: 4 of 6 agree.\nThis is authored fixture agreement, not measured AI accuracy.',10,'baseline-check');
  await page.locator('[data-action="clip"][data-id="train-negative-01"]').click();
  await click('play');
  await page.waitForFunction(() => document.querySelector('#evidence-video')?.currentTime > 0.5);
  await scene('A shoulder stop is a hard negative: stopped does not mean blocking a lane.\nCorrections use TRAIN examples only; holdout labels stay out of generation.',10,'negative-video');
  await click('correct');
  await page.getByRole('dialog').waitFor();
  await scene('Teach the boundary with the shoulder stop and slow-moving traffic.\nA new rule version preserves the earlier one.',8,'correction');
  await click('confirm-correct');
  await page.getByRole('dialog').waitFor({state:'hidden'});
  state=await apiState();
  assert.equal(state.versions.length,2);
  await scene('Version 2 makes the exclusions explicit.\nThe history remains inspectable and the evaluation stays separate.',8,'corrected-rule');
  await click('evaluate');
  await page.locator('.scoreboard').waitFor();
  state=await apiState();
  assert.equal(state.evaluations.at(-1).metrics.correct,6);
  assert.equal(state.evaluations.at(-1).metrics.falsePositives,0);
  assert.equal(state.evaluations.at(-1).holdoutDigest,state.evaluations[0].holdoutDigest);
  await scene('The corrected rule agrees with all six authored scenarios.\nBecause this set was checked before, this is a regression check, not unseen validation.',10,'corrected-check');
  await click('publish');
  await page.locator('[data-action="replay"]:enabled').waitFor();
  await scene('Publish the evaluated version in this local demo workspace.\nOperational events will retain the exact rule that produced them.',7,'publish');
  await click('replay');
  await page.locator('.ledger-table tbody tr').waitFor();
  assert.equal(await page.locator('.ledger-table tbody tr').count(),1);
  state=await apiState();
  assert.equal(state.ledger.length,1);
  await scene('Replay a separate clip and create an evidence-linked event.\nThe ledger records its source, rule version, time window, and decision.',10,'ledger');
  await click('replay');
  await page.getByRole('status').filter({hasText:'already has an event'}).waitFor();
  assert.equal((await apiState()).ledger.length,1);
  await scene('Replay again: still one event.\nThe deduplication key prevents duplicate operational records.',6,'deduplication');
  await page.locator('[data-action="evidence"]').click();
  await page.getByRole('dialog').waitFor();
  await page.locator('.evidence-detail video').evaluate(video=>video.play());
  await scene('Open the receipt: original clip, evidence window, and pinned rule.\nSynthetic provenance is visible beside the decision.',10,'evidence');
  await page.getByRole('button',{name:'Back to studio',exact:true}).click();
  await page.getByRole('button',{name:'Activity log',exact:true}).click();
  await page.getByRole('dialog').waitFor();
  await scene('Export the audit trail and evidence bundle.\nReal VAST, Cosmos, and W&B integrations are separate and require server credentials.',8,'audit');
  const downloadEvent=page.waitForEvent('download');
  await click('export');
  const download=await downloadEvent;
  await download.saveAs(path.join(out,'showonce-evidence.json'));
  await page.getByRole('button',{name:'Done',exact:true}).click();
  await page.getByRole('button',{name:'Provider connections',exact:true}).click();
  await scene('Three real adapters, with credentials held on the server.\nLIVE EXECUTION UNVERIFIED. This fixture run is not a final contest demonstration.',9,'provider-connections');
  await page.getByRole('button',{name:'Done',exact:true}).click();
  await page.locator('#workspace').scrollIntoViewIfNeeded();
  await scene('Show examples. Test the boundary. Publish the event.\nSource and setup: github.com/TurpoFIN/showonce',7,'closing');
  const mobile = await browser.newContext({viewport:{width:390,height:844},isMobile:true,deviceScaleFactor:1});
  const mobilePage = await mobile.newPage();
  await mobilePage.goto(baseURL,{waitUntil:'networkidle'});
  await mobilePage.getByRole('heading',{name:'Teach your cameras what matters.'}).waitFor();
  assert.equal(await mobilePage.evaluate(()=>document.documentElement.scrollWidth > innerWidth),false,'Mobile page overflows horizontally');
  await mobilePage.screenshot({path:path.join(out,'mobile.png'),fullPage:true});
  await mobile.close();
  assert.deepEqual(errors,[],'Browser JavaScript errors');
  state=await apiState();
  await writeFile(path.join(out,'run.json'),JSON.stringify({status:'passed',mode:'synthetic-demo',recordedAt:new Date().toISOString(),durationSeconds:clock(),baseline:state.evaluations[0].metrics,corrected:state.evaluations.at(-1).metrics,ledgerCount:state.ledger.length,javascriptErrors:errors,disclaimer:'Actual UI recording. Synthetic footage and deterministic decisions. No sponsor inference executed.'},null,2));
  success=true;
} catch(error) {
  await page.screenshot({path:path.join(out,'failure.png'),fullPage:true}).catch(()=>{});
  await writeFile(path.join(out,'failure.json'),JSON.stringify({status:'failed',message:error.message,javascriptErrors:errors},null,2));
  throw error;
} finally {
  const video=page.video();
  await context.close();
  await copyFile(await video.path(),path.join(out,'showonce-demo.webm'));
  await writeFile(path.join(out,'captions.srt'),subtitle.map((s,i)=>`${i+1}\n${srtTime(s.begin)} --> ${srtTime(s.end)}\n${s.text}\n`).join('\n'));
  const assTime = s => { const cs=Math.round(s*100); return `${Math.floor(cs/360000)}:${String(Math.floor(cs/6000)%60).padStart(2,'0')}:${String(Math.floor(cs/100)%60).padStart(2,'0')}.${String(cs%100).padStart(2,'0')}`; };
  const assHeader = '[Script Info]\nScriptType: v4.00+\nPlayResX: 1440\nPlayResY: 1112\n\n[V4+ Styles]\nFormat: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding\nStyle: Default,DejaVu Sans,26,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,1.5,0,2,50,50,24,1\n\n[Events]\nFormat: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\n';
  await writeFile(path.join(out,'captions.ass'),assHeader+subtitle.map(s=>`Dialogue: 0,${assTime(s.begin)},${assTime(s.end)},Default,,0,0,0,,${s.text.replaceAll('\n','\\N')}`).join('\n')+'\n');
  await browser.close();
  console.log(success?'Recorded and verified the complete demo UI loop.':'Saved browser evidence for the failed run.');
}
